export default [
  {
    url: require("./file/m1.mp3"),
    title: "បើអស់ចិត្ត ｜ លោក កែវ វាសនា ｜ Live Band Pattaya Music & Pub Happy Everyday",
    artist: "Keo Veasna",
    artwork: require("./file/m1.png"),
    duration: 251,
  },
  {
    url: require("./file/m2.mp3"),
    title: "ចង់វិលរកសង្សារចាស់ ｜ លោក កែវ វាសនា ｜ Live Band Pattaya Music & Pub Happy Everyday",
    artist: "Keo Veasna",
    artwork: require("./file/m1.png"),
    duration: 251,
  },
  {
    url: "https://rntp.dev/example/Longing.mp3",
    title: "Longing",
    artist: "David Chavez",
    artwork: "https://rntp.dev/example/Longing.jpeg",
    duration: 143,
  },
  {
    url: "https://rntp.dev/example/Soul%20Searching.mp3",
    title: "Soul Searching (Demo)",
    artist: "David Chavez",
    artwork: "https://rntp.dev/example/Soul%20Searching.jpeg",
    duration: 77,
  },
  {
    url: "https://rntp.dev/example/Lullaby%20(Demo).mp3",
    title: "Lullaby (Demo)",
    artist: "David Chavez",
    artwork: "https://rntp.dev/example/Lullaby%20(Demo).jpeg",
    duration: 71,
  },
  {
    url: "https://rntp.dev/example/Rhythm%20City%20(Demo).mp3",
    title: "Rhythm City (Demo)",
    artist: "David Chavez",
    artwork: "https://rntp.dev/example/Rhythm%20City%20(Demo).jpeg",
    duration: 106,
  },
  {
    url: "https://rntp.dev/example/hls/whip/playlist.m3u8",
    title: "Whip",
    artist: "prazkhanal",
    artwork: "https://rntp.dev/example/hls/whip/whip.jpeg",
    type: "hls",
  },
  {
    url: "https://ais-sa5.cdnstream1.com/b75154_128mp3",
    title: "Smooth Jazz 24/7",
    artist: "New York, NY",
    artwork: "https://rntp.dev/example/smooth-jazz-24-7.jpeg",
    isLiveStream: true,
  },
  {
    url: "https://traffic.libsyn.com/atpfm/atp545.mp3",
    title: "Chapters",
  },
  {
    url: "https://kut.streamguys1.com/kutx-app.aac?listenerId=123456784123",
    title: "KUTX",
  },
];
